# model params:
iterations: 1000
depth: 8
learning_rate: 0.05,
l2_leaf_reg: 3,
random_seed: 42
verbose: 100

index_col: 'flat_id'
target_col: 'target'
one_hot_drop: 'if_binary'
n_splits: 5
scoring: ['neg_root_mean_squared_error', 'r2', 'neg_mean_absolute_error']
n_jobs: -1
shuffle: True